### ISSUE TITLE
font-matrix.md / question

### ISSUE THREAD

**Issue by d-j-a-y** [jcome/sif.font#2]
- tool-showlayer : is it normal the icon in grey level ?
- tool-hidelayer : an eye with cross block ? kind of ![this kind of](https://cdn3.iconfinder.com/data/icons/unicons-vector-icons-pack/32/eye-cross-128.png)

**Comment by jcome** [comment]
personally prefer not use a line to represent "Close". But anyway, I added as alter versions:
https://github.com/jcome/sif.font/blob/master/output/glyphs/eye-close-1.png
https://github.com/jcome/sif.font/blob/master/output/glyphs/eye-open-1.png
